--gtk-version=4
--ozone-platform=wayland
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--enable-accelerated-video-decode
--ignore-gpu-blocklist
--enable-zero-copy
--disable-reading-from-canvas
