require('common.settings')
require('common.keymaps')
require('plugins.gruvbox')
require('plugins.copilot')
require('plugins.complete')
require('plugins.installer')
require('plugins.formatters')
require('plugins.servers')

vim.lsp.set_log_level('debug')
