# Dracula-inspired color scheme
primary: &primary
  foreground: f8f8f2ff

secondary: &secondary
  foreground: 6272a4ff

background: &background
  color: 282a36e6

accent1: &accent1
  foreground: 50fa7bff # Green

accent2: &accent2
  foreground: f1fa8cff # Yellow

accent3: &accent3
  foreground: ff79c6ff # Pink

accent4: &accent4
  foreground: 8be9fdff # Cyan

alert: &alert
  foreground: ff5555ff # Red

# Base element styling
segment-style: &segment-style
  deco:
    stack:
      - border:
          size: 2
          color: 00000000 # Invisible border for spacing
      - background:
          color: 44475a66 # Slightly lighter than background
      - border:
          size: 2
          radius: 5
          color: 00000000

  font:
    - Fira Code Nerd Font:size=12
    - Material Design Icons:size=14

  left-margin: 8
  right-margin: 8
  spacing: 2

# Module templates
module-wrapper: &module-wrapper
  content:
    list:
      spacing: 0
      items:
        - string:
            deco:
              border:
                size: 0
                radius: 5
                color: 00000000
            text: ""
            font: Fira Code Nerd Font:size=16
            <<: *secondary
        - content: CONTENT_PLACEHOLDER
        - string:
            deco:
              border:
                size: 0
                radius: 5
                color: 00000000
            text: ""
            font: Fira Code Nerd Font:size=16
            <<: *secondary

bar:
  location: top
  height: 34
  spacing: 2
  margin: 4
  background: *background
  border:
    width: 0
    margin: 0

  left:
    - foreign-toplevel:
        content:
          map:
            conditions:
              activated:
                string:
                  text: "  {title}"
                  <<: [*segment-style, *primary]

  right:
    - network:
        poll-interval: 1000
        content:
          <<: *module-wrapper
          substitute:
            CONTENT_PLACEHOLDER:
              map:
                conditions:
                  name == wlp1s0:
                    map:
                      conditions:
                        state == up:
                          list:
                            items:
                              - string:
                                  { text: "", <<: [*segment-style, *accent1] }
                              - string:
                                  {
                                    text: "{ssid}",
                                    <<: [*segment-style, *primary],
                                  }
                              - string:
                                  {
                                    text: "{ul-speed:mb} {dl-speed:mb}",
                                    <<: [*segment-style, *secondary],
                                  }
                        state == down:
                          string:
                            { text: " OFFLINE", <<: [*segment-style, *alert] }

    - cpu:
        poll-interval: 1000
        content:
          <<: *module-wrapper
          substitute:
            CONTENT_PLACEHOLDER:
              list:
                items:
                  - ramp:
                      tag: cpu
                      items:
                        - string: { text: "", <<: [*segment-style, *accent1] }
                        - string: { text: "", <<: [*segment-style, *accent2] }
                        - string: { text: "", <<: [*segment-style, *accent3] }
                        - string: { text: "", <<: [*segment-style, *alert] }
                  - string: { text: "{cpu}%", <<: [*segment-style, *primary] }

    - mem:
        poll-interval: 1000
        content:
          <<: *module-wrapper
          substitute:
            CONTENT_PLACEHOLDER:
              list:
                items:
                  - ramp:
                      tag: mem
                      items:
                        - string: { text: "", <<: [*segment-style, *accent1] }
                        - string: { text: "", <<: [*segment-style, *accent2] }
                        - string: { text: "", <<: [*segment-style, *accent3] }
                        - string: { text: "", <<: [*segment-style, *alert] }
                  - string:
                      { text: "{used:0.1f}G", <<: [*segment-style, *primary] }

    - pipewire:
        content:
          <<: *module-wrapper
          substitute:
            CONTENT_PLACEHOLDER:
              map:
                conditions:
                  muted:
                    string: { text: " MUTED", <<: [*segment-style, *alert] }
                  cubic_volume < 33:
                    list:
                      items:
                        - string: { text: "", <<: [*segment-style, *accent1] }
                        - string:
                            {
                              text: "{cubic_volume}%",
                              <<: [*segment-style, *primary],
                            }
                  cubic_volume < 66:
                    list:
                      items:
                        - string: { text: "", <<: [*segment-style, *accent2] }
                        - string:
                            {
                              text: "{cubic_volume}%",
                              <<: [*segment-style, *primary],
                            }
                  default:
                    list:
                      items:
                        - string: { text: "", <<: [*segment-style, *accent3] }
                        - string:
                            {
                              text: "{cubic_volume}%",
                              <<: [*segment-style, *primary],
                            }

    - battery:
        name: BAT1
        poll-interval: 30000
        content:
          <<: *module-wrapper
          substitute:
            CONTENT_PLACEHOLDER:
              map:
                conditions:
                  state == charging:
                    list:
                      items:
                        - string: { text: "", <<: [*segment-style, *accent1] }
                        - string:
                            {
                              text: "{capacity}%",
                              <<: [*segment-style, *primary],
                            }
                  default:
                    list:
                      items:
                        - ramp:
                            tag: capacity
                            items:
                              - string:
                                  { text: "", <<: [*segment-style, *alert] }
                              - string:
                                  { text: "", <<: [*segment-style, *accent3] }
                              - string:
                                  { text: "", <<: [*segment-style, *accent2] }
                              - string:
                                  { text: "", <<: [*segment-style, *accent1] }
                              - string:
                                  { text: "", <<: [*segment-style, *accent1] }
                        - string:
                            {
                              text: "{capacity}%",
                              <<: [*segment-style, *primary],
                            }

    - clock:
        date-format: "%a %d %b"
        time-format: "%H:%M"
        content:
          <<: *module-wrapper
          substitute:
            CONTENT_PLACEHOLDER:
              list:
                items:
                  - string:
                      { text: " {date}", <<: [*segment-style, *secondary] }
                  - string: { text: " {time}", <<: [*segment-style, *primary] }
