catppuccin-base: &catppuccin-base
  color: "1e1e2eff"

catppuccin-subtext0: &catppuccin-subtext0
  foreground: "a6adc8ff"

catppuccin-text: &catppuccin-text
  foreground: "cdd6f4ff"

catppuccin-green: &catppuccin-green
  foreground: "a6e3a1ff"

catppuccin-peach: &catppuccin-peach
  foreground: "fab387ff"

catppuccin-red: &catppuccin-red
  foreground: "f38ba8ff"

catppuccin-blue: &catppuccin-blue
  foreground: "89b4faff"

catppuccin-sapphire: &catppuccin-sapphire
  foreground: "74c7ecff"

catppuccin-mauve: &catppuccin-mauve
  foreground: "cba6f7ff"

catppuccin-pink: &catppuccin-pink
  foreground: "f5c2e7ff"

middle: &middle
  deco:
    stack:
      - background:
          <<: *catppuccin-base
      - border:
          size: 0
          color: "00000000"
  font: "Iosevka Term Extended:size=26"
  left-margin: 6
  right-margin: 6

separator: &separator
  text: ""
  <<: *catppuccin-subtext0
  font: "Iosevka Term Extended:size=12:style=solid"
  right-margin: 8
  left-margin: 8

bar:
  location: top
  height: 40
  spacing: 0
  margin: 0

  border:
    width: 1
    color: "42445aff"

  foreground: "cdd6f4cc"
  background: "1e1e2ecc"

  left:
    - foreign-toplevel:
        content:
          map:
            default:
              list:
                spacing: 0
                items:
                  - string:
                      text: "{title}"
                      <<:
                        - *catppuccin-text
                        - *middle
            conditions:
              ~activated:
                empty:
                  margin: 0
                  deco:
                    border:
                      size: 0
                      color: "00000000"
              activated:
                list:
                  spacing: 0
                  items:
                    - string:
                        text: "{title}"
                        <<:
                          - *catppuccin-text
                          - *middle
  right:
    - network:
        poll-interval: 1000
        content:
          list:
            spacing: 0
            items:
              - map:
                  conditions:
                    name == lo || name == sit0:
                      empty:
                        margin: 0
                        deco:
                          border:
                            size: 0
                            color: "00000000"
                    name == enp193s0f3u1:
                      list:
                        spacing: 0
                        items:
                          - string:
                              text: " {dl-speed:mb}/{ul-speed:mb}"
                              <<:
                                - *catppuccin-sapphire
                                - *middle
                          - map:
                              conditions:
                                ~carrier:
                                  string:
                                    text: " Down"
                    name == wlp1s0:
                      list:
                        spacing: 0
                        items:
                          - string:
                              text: " {ssid} {dl-speed:mb}/{ul-speed:mb}"
                              <<:
                                - *catppuccin-sapphire
                                - *middle
                  default:
                    empty:
                      margin: 0
                      deco:
                        border:
                          size: 0
                          color: "00000000"
    - label:
        content:
          string: *separator
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id < 0:
                list:
                  spacing: 0
                  items:
                    - string:
                        text: ""
                        <<:
                          - *catppuccin-pink
                          - *middle
                    - ramp:
                        tag: cpu
                        items:
                          - string:
                              text: " "
                              <<: *catppuccin-green
                          - string:
                              text: " "
                              <<: *catppuccin-peach
                          - string:
                              text: " "
                              <<: *catppuccin-red
                    - string:
                        text: "{cpu}%"
                        <<:
                          - *catppuccin-subtext0
                          - *middle
    - label:
        content:
          string: *separator
    - mem:
        poll-interval: 1000
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: ""
                  <<:
                    - *catppuccin-mauve
                    - *middle
              - ramp:
                  tag: mem
                  items:
                    - string:
                        text: " "
                        <<: *catppuccin-green
                    - string:
                        text: " "
                        <<: *catppuccin-peach
                    - string:
                        text: " "
                        <<: *catppuccin-red
              - string:
                  text: "{used:gb}G"
                  <<:
                    - *catppuccin-subtext0
                    - *middle
    - label:
        content:
          string: *separator
    - backlight:
        name: amdgpu_bl0
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: ""
                  <<:
                    - *catppuccin-blue
                    - *middle
              - ramp:
                  tag: percent
                  items:
                    - string:
                        text: " "
                        <<: *catppuccin-green
                    - string:
                        text: " "
                        <<: *catppuccin-peach
                    - string:
                        text: " "
                        <<: *catppuccin-red
              - string:
                  text: "{percent}%"
                  <<:
                    - *catppuccin-subtext0
                    - *middle
    - label:
        content:
          string: *separator
    - pipewire:
        content:
          list:
            spacing: 0
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          form_factor == "speaker":
                            list:
                              spacing: 0
                              items:
                                - map:
                                    conditions:
                                      muted:
                                        list:
                                          spacing: 0
                                          items:
                                            - string:
                                                text: ""
                                                <<:
                                                  - *catppuccin-red
                                                  - *middle
                                            - string:
                                                text: "{cubic_volume}%"
                                                <<:
                                                  - *catppuccin-subtext0
                                                  - *middle
                                      ~muted:
                                        list:
                                          spacing: 0
                                          items:
                                            - string:
                                                text: ""
                                                <<:
                                                  - *catppuccin-blue
                                                  - *middle
                                            - string:
                                                text: "{cubic_volume}%"
                                                <<:
                                                  - *catppuccin-subtext0
                                                  - *middle
                          form_factor == "headphone":
                            list:
                              spacing: 0
                              items:
                                - map:
                                    conditions:
                                      muted:
                                        list:
                                          spacing: 0
                                          items:
                                            - string:
                                                text: ""
                                                <<:
                                                  - *catppuccin-red
                                                  - *middle
                                            - string:
                                                text: "{cubic_volume}%"
                                                <<:
                                                  - *catppuccin-subtext0
                                                  - *middle
                                      ~muted:
                                        list:
                                          spacing: 0
                                          items:
                                            - string:
                                                text: ""
                                                <<:
                                                  - *catppuccin-blue
                                                  - *middle
                                            - string:
                                                text: "{cubic_volume}%"
                                                <<:
                                                  - *catppuccin-subtext0
                                                  - *middle
                    type == "source":
                      list:
                        spacing: 0
                        items:
                          - map:
                              conditions:
                                muted:
                                  list:
                                    spacing: 0
                                    items:
                                      - string:
                                          text: ""
                                          <<:
                                            - *catppuccin-red
                                            - *middle
                                      - string:
                                          text: "MUTED"
                                          <<:
                                            - *catppuccin-subtext0
                                            - *middle
                                ~muted:
                                  list:
                                    spacing: 0
                                    items:
                                      - string:
                                          text: ""
                                          <<:
                                            - *catppuccin-green
                                            - *middle
                                      - string:
                                          text: "ON"
                                          <<:
                                            - *catppuccin-subtext0
                                            - *middle
                    default:
                      empty:
                        margin: 0
                        deco:
                          border:
                            size: 0
                            color: "00000000"
    - label:
        content:
          string: *separator
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          map:
            conditions:
              state == unknown:
                list:
                  spacing: 0
                  items:
                    - string:
                        text: " {capacity}%"
                        <<:
                          - *catppuccin-red
                          - *middle

              state == discharging:
                list:
                  spacing: 0
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-red
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-peach
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-blue
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-blue
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-green
                                - *middle
                    - string:
                        text: "{capacity}% {estimate}"
                        <<:
                          - *catppuccin-subtext0
                          - *middle
              state == charging:
                list:
                  spacing: 0
                  items:
                    - string:
                        text: ""
                        <<:
                          - *catppuccin-blue
                          - *middle
                    - string:
                        text: "{capacity}% {estimate}"
                        <<:
                          - *catppuccin-green
                          - *middle
              state == full:
                list:
                  spacing: 0
                  items:
                    - string:
                        text: " {capacity}%"
                        <<:
                          - *catppuccin-green
                          - *middle
              state == "not charging":
                list:
                  spacing: 0
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-red
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-peach
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-blue
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-blue
                                - *middle
                          - string:
                              text: ""
                              <<:
                                - *catppuccin-green
                                - *middle
                    - string:
                        text: "{capacity}% {estimate}"
                        <<:
                          - *catppuccin-subtext0
                          - *middle
    - label:
        content:
          string: *separator
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: " {date} {time}"
                  <<:
                    - *catppuccin-text
                    - *middle
