std_overline: &std_overline { overline: { size: 1, color: ddddddff } }

bar:
  location: top
  height: 64
  spacing: 5
  margin: 7

  font: Iosevka Term Extended:size=22,Consolas
  foreground: ffffff66
  background: 00000000

  border:
    width: 0

  left:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: { empty: {} }
              activated:
                - string: { text: "{title}" }
  right:
    - network:
        content:
          map:
            default: { empty: {} }
            conditions:
              name == enp193s0f3u1:
                map:
                  conditions:
                    ~carrier: { empty: {} }
                    carrier:
                      map:
                        default:
                          {
                            string:
                              {
                                text: "",
                                foreground: ff000066,
                                font: Font Awesome 6 Free:style=solid:size=22,
                              },
                          }
                        conditions:
                          state == up && ipv4 != "":
                            { string: { text: "", foreground: 00ff00ff } }
    - network:
        poll-interval: 1000
        content:
          map:
            default: { empty: {} }
            conditions:
              name == wlp1s0:
                map:
                  default: { string: { text: , foreground: ffffff66 } }
                  conditions:
                    state == down: { string: { text: , foreground: ff0000ff } }
                    state == up:
                      map:
                        default:
                          - string: { text: "", foreground: 00ff00ff }
                          - string:
                              {
                                text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s",
                                foreground: ffffff66,
                              }
                        conditions:
                          ipv4 == "":
                            - string: { text: , foreground: ffffff66 }
                            - string:
                                {
                                  text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s",
                                  foreground: ffffff66,
                                }
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id < 0:
                - string:
                    {
                      text: "  ",
                      foreground: 00a0ffff,
                      font: Font Awesome 6 Free:style=solid:size=22,
                    }
                - ramp:
                    tag: cpu
                    items:
                      - string: { text: ▁ }
                      - string: { text: ▂ }
                      - string: { text: ▃ }
                      - string: { text: ▄ }
                      - string: { text: ▅ }
                      - string: { text: ▆ }
                      - string: { text: ▇ }
                      - string: { text: █ }
    - mem:
        poll-interval: 1000
        content:
          - string:
              {
                text: "",
                foreground: 00a0ffff,
                font: Font Awesome 6 Free:style=solid:size=22,
              }
          - string: { text: "{used:gb}/{total:gb}" }
    - backlight:
        name: amdgpu_bl0
        content:
          [
            string:
              {
                text: "",
                foreground: 00a0ffff,
                font: Font Awesome 6 Free:style=solid:size=22,
              },
            string: { text: "{percent}%" },
          ]
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                - map:
                    conditions:
                      form_factor == "speaker":
                        map:
                          conditions:
                            cubic_volume <= 0:
                              string:
                                {
                                  text: "",
                                  foreground: a00000ff,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                            cubic_volume < 33:
                              string:
                                {
                                  text: "",
                                  foreground: 00a0ff00,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                            cubic_volume < 66:
                              string:
                                {
                                  text: "",
                                  foreground: 00ff00ff,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                            else:
                              string:
                                {
                                  text: "",
                                  foreground: ffa600ff,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                      form_factor == "headphone":
                        map:
                          conditions:
                            cubic_volume <= 0:
                              string:
                                {
                                  text: "",
                                  foreground: a00000ff,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                            cubic_volume < 33:
                              string:
                                {
                                  text: "",
                                  foreground: 00a0ff00,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                            cubic_volume < 66:
                              string:
                                {
                                  text: "",
                                  foreground: 00ff00ff,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                            else:
                              string:
                                {
                                  text: "",
                                  foreground: ffa600ff,
                                  font: Font Awesome 6 Free:style=solid:size=22,
                                }
                      else:
                        string: { text: "" }
                - map:
                    conditions:
                      ~muted:
                        string: { text: " {cubic_volume}%" }
                      muted:
                        string: { text: "", foreground: ff0000ff }
    - battery:
        name: BAT1
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: { text: , foreground: ff0000ff }
                      - string: { text: , foreground: ffa600ff }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text: , foreground: 00ff00ff }
                - string: { text: "{capacity}% {estimate}" }
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: { text: , foreground: 00ff00ff }
                - string: { text: "{capacity}% {estimate}" }
              state == full:
                - string: { text: , foreground: 00ff00ff }
                - string: { text: "{capacity}% full" }
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: { text:  , foreground: ff0000ff }
                      - string: { text:  , foreground: ffa600ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                      - string: { text:  , foreground: 00ff00ff }
                - string: { text: "{capacity}%" }
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: { text: "{date}", right-margin: 5 }
          - string: { text:  }
          - string: { text: "{time}" }
    - label:
        content:
          string:
            on-click: systemctl poweroff
            text: 
