vo=gpu-next
gpu-api=vulkan
target-colorspace-hint=yes
target-colorspace-hint-mode=source

tone-mapping=hable
target-peak=auto
hdr-compute-peak=yes

[sdr-icc]
icc-profile=/home/amitprakash/.local/share/color/icc/samsung-g93sc/S49CG93xS.icm
target-colorspace-hint-mode=target
