CompileFlags:
  Add: [-std=c++23, -Wall, -Wno-missing-prototypes, -Werror]
Diagnostics:
  ClangTidy:
    Add: [performance*, modernize*, readability*]
    CheckOptions:
      readability-identifier-naming.VariableCase: camelBack 
      readability-identifier-naming.PublicMethodCase: lower_case
      readability-identifier-naming.NamespaceCase: lower_case
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.PrivateMemberPrefix: m_
      readability-identifier-naming.PrivateMemberCase: lower_case
      readability-identifier-naming.StructCase: CamelCase
      readability-identifier-naming.FunctionCase: lower_case
      readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      readability-identifier-naming.StaticConstant: UPPER_CASE
